### PR TITLE
changes for compatibility with 16.5.0

### PR DESCRIPTION
**Pull request by tomzo**
see https://github.com/gocd/gocd/issues/2203

### CODE REVIEW

**Comment by ketan** [comment]
For now do you feel it's OK to get rid of the old messages in favor of the new ones? The `plugin.xml` already has a field to specify minimum version of go that the plugin supports?

**Comment by tomzo** [comment]
Now it might not work, when I was debugging I found that both new and old messages are received by plugin. We should make that consistent in server first. Then remove old onces from here.

**Comment by ketan** [comment]
> Now it might not work, when I was debugging I found that both new and old messages are received by plugin. We should make that consistent in server first. Then remove old onces from here.

Could you log a bug about these dups on gocd/gocd please?

**Comment by tomzo** [comment]
added https://github.com/gocd/gocd/issues/2206

**Pull request merged**
